[package]
name = "sysconf"
version = "0.1.0"
authors = ["Gary M. Josack <gary@byoteki.com>"
repository = "https://github.com/gmjosack/procure"
license = "Apache-2.0"
description = "Small safe wrapper around sysconf"

[dependencies]
sysconf = "*"

